# function-config.yaml

runtime: python39
entrypoint: handle_webhook
service_account: data-integration@${PROJECT_ID}.iam.gserviceaccount.com

env_variables:
  REDIS_INSTANCE: ${REDIS_INSTANCE}
  PROJECT_ID: ${PROJECT_ID}
  REGION: ${REGION}

vpc_connector: projects/${PROJECT_ID}/locations/${REGION}/connectors/vpc-connector

labels:
  environment: production
  service: chatbot
  team: ai-ml

available_memory_mb: 256
timeout_seconds: 60
max_instances: 100
min_instances: 5

ingress_settings: "ALLOW_INTERNAL_ONLY"
